// <auto-generated />
using System;
using System.Data.Entity;
using SimpleWebAppMVC.Data;

namespace SimpleWebAppMVC.Migrations
{
    // EntityFrameworkCore references removed for .NET Framework compatibility
    // Migration and model builder logic must be rewritten for classic Entity Framework
    // This file is now a placeholder and should be replaced with EF6 migration logic if needed
}
